tunnel: YOUR_TUNNEL_ID_HERE
credentials-file: /etc/cloudflared/YOUR_TUNNEL_ID_HERE.json

ingress:
  # Main domain
  - hostname: uitleenschrift.nl
    service: http://host.docker.internal:5000
  # WWW subdomain  
  - hostname: www.uitleenschrift.nl
    service: http://host.docker.internal:5000
  # Catch-all rule (required)
  - service: http_status:404
