version: '3.8'

services:
  app:
    image: hoite/uitleenschrift:latest
    container_name: uitleenschrift-app
    ports:
      - "5001:5000"
    environment:
      - FLASK_ENV=production
      - SECRET_KEY=${SECRET_KEY}
      - GOOGLE_BOOKS_API_KEY=${GOOGLE_BOOKS_API_KEY}
      - DATABASE_URL=sqlite:////app/instance/uitleenschrift.db
    volumes:
      - ./instance:/app/instance
    restart: unless-stopped
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Optioneel: Watchtower voor automatische updates
  watchtower:
    image: containrrr/watchtower
    container_name: uitleenschrift-watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_INCLUDE_STOPPED=true
      - WATCHTOWER_POLL_INTERVAL=300  # Check elke 5 minuten
      - WATCHTOWER_LABEL_ENABLE=true
    labels:
      - "com.centurylinklabs.watchtower.enable=false"  # Watchtower zichzelf niet updaten
    restart: unless-stopped

networks:
  default:
    name: uitleenschrift-network
